spring:
  application:
    name: service-item
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://mysql-service.glsx:3306/item?useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 1234
  data:
    redis:
      host: item-redis-qz94.glsx
      port: 6379
      database: 0

server:
  port: 8080

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:/mapper/**/*.xml
  type-aliases-package: com.atguigu.cloud.domain

